### ISSUE TITLE
Senparc.Xncf.XncfBuilder项目中缺少PromptPlugins文件夹

### ISSUE THREAD

**Issue by joyyangfan** [NeuCharFramework/NcfPackageSources#188]

**Comment by JeffreySu** [comment]
@joyyangfan 之前在群里面有发送单独的文件包，请关注。另外下一个 XncfBuilder 版本将引用新版 PromptRange，我们将不再需要 Prompt 文件，全部使用数据库管理。

**Comment by JeffreySu** [comment]
#209

**Comment by JeffreySu** [comment]
@joyyangfan 已经完成升级，目前已经不再需要以来 Plugins 文件夹，可以直接导入到 PromptRange 进行操作。
